name: doubly_linked_list
description: A non-intrusive doubly linked list with O(1) removals/insertions. Ideal for LRU caches, queues, and frequent mid-list modifications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
